services:
  dockeroperator:
    build:
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/app
    attach: false
    env_file: ".env"
    ports:
      - 8080:8080
      - 80:80
      - 443:443
